apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: chatbtv
  name: open-webui-pvc
  namespace: chatbtv
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 2Gi
